#!/bin/sh
test -d /var/lib/letsencrypt/.well-known 
certbot --webroot --webroot-path /var/lib/letsencrypt/ --agree-tos --email ${EMAIL} certonly -n -d ${DOMAIN}
cp /etc/letsencrypt/live/${DOMAIN}/privkey.pem /etc/ssl/${DOMAIN}.key
cp /etc/letsencrypt/live/${DOMAIN}/fullchain.pem /etc/ssl/${DOMAIN}.crt
